In [29]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing import image

In [35]:
image1 = image.load_img('train/dog_image.jpg',target_size=(200,200))

In [36]:
img_array = image.img_to_array(image1)
print(img_array.shape)

(200, 200, 3)


In [37]:
print("Top-left pixel:", img_array[0, 0])      # [R, G, B] values
print("Center pixel:", img_array[128, 128])

Top-left pixel: [225. 228. 233.]
Center pixel: [139. 130. 123.]


In [38]:
import numpy as np
np.set_printoptions(threshold=np.inf)  # disable truncation
print(img_array)



[[[225. 228. 233.]
  [225. 228. 233.]
  [225. 228. 233.]
  [225. 228. 233.]
  [225. 228. 233.]
  [226. 229. 234.]
  [226. 229. 234.]
  [226. 229. 234.]
  [226. 229. 234.]
  [224. 229. 233.]
  [224. 229. 233.]
  [224. 229. 233.]
  [223. 228. 232.]
  [223. 228. 232.]
  [225. 228. 233.]
  [225. 228. 233.]
  [225. 228. 233.]
  [225. 228. 233.]
  [224. 229. 235.]
  [224. 229. 235.]
  [224. 229. 235.]
  [224. 229. 235.]
  [225. 230. 236.]
  [227. 230. 235.]
  [227. 230. 235.]
  [227. 230. 235.]
  [227. 230. 235.]
  [225. 230. 236.]
  [225. 230. 236.]
  [225. 230. 236.]
  [225. 230. 236.]
  [225. 230. 236.]
  [224. 229. 235.]
  [224. 229. 235.]
  [224. 229. 235.]
  [224. 229. 235.]
  [221. 228. 234.]
  [221. 228. 234.]
  [221. 228. 234.]
  [221. 228. 234.]
  [221. 228. 234.]
  [222. 227. 233.]
  [223. 228. 234.]
  [223. 228. 234.]
  [224. 229. 235.]
  [224. 229. 235.]
  [224. 229. 235.]
  [224. 229. 235.]
  [224. 229. 235.]
  [224. 229. 235.]
  [221. 228. 234.]
  [221. 228. 234.]
  [220. 227.

In [41]:
type(image1)

PIL.Image.Image

In [42]:
datagen = ImageDataGenerator(
    rotation_range = 30,
    width_shift_range = 0.2,
    height_shift_range = 0.2,
    shear_range = 0.2,
    zoom_range = 0.2,
    horizontal_flip = True
)

In [43]:
img = image.img_to_array(image1)

In [44]:
type(img)

numpy.ndarray

In [47]:
input_batch = img.reshape(1,200,200,3)

In [48]:
input_batch.shape

(1, 200, 200, 3)

In [51]:
i = 0
for output in datagen.flow(input_batch, batch_size = 1, save_to_dir= 'aug'):
    i = i + 1

    if i ==10:
      break

In [52]:
input_batch.shape

(1, 200, 200, 3)