In [ ]:
import numpy as np

docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [ ]:
tokenizer.fit_on_texts(docs)

In [ ]:
tokenizer.word_counts

OrderedDict([('go', 1),
             ('india', 4),
             ('hip', 2),
             ('hurray', 1),
             ('jeetega', 3),
             ('bhai', 1),
             ('bharat', 1),
             ('mata', 1),
             ('ki', 2),
             ('jai', 2),
             ('kohli', 2),
             ('sachin', 2),
             ('dhoni', 2),
             ('modi', 1),
             ('ji', 1),
             ('inquilab', 1),
             ('zindabad', 1)])

In [ ]:
tokenizer.word_index

{'india': 1,
 'jeetega': 2,
 'hip': 3,
 'ki': 4,
 'jai': 5,
 'kohli': 6,
 'sachin': 7,
 'dhoni': 8,
 'go': 9,
 'hurray': 10,
 'bhai': 11,
 'bharat': 12,
 'mata': 13,
 'modi': 14,
 'ji': 15,
 'inquilab': 16,
 'zindabad': 17}

In [ ]:
len(tokenizer.word_index)

17

In [ ]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [ ]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')
sequences

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]], dtype=int32)

In [ ]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense, SimpleRNN, Embedding, Flatten

In [ ]:
# model = Sequential()
# model.add(Embedding(17,output_dim=2,input_length=5))

# model.summary()

#  17 - total number of unique words
#  output_dim - output dimention, 2 mean every word is represented by two numbers
# input_length - how many words


from keras import Sequential
from keras.layers import Dense,Flatten,Embedding

model = Sequential()
model.add(Embedding(18,output_dim=2,input_length=5))

model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_9 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile('adam','accuracy')

In [ ]:
pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step
[[[-0.03030254 -0.03903904]
  [-0.0256271   0.03285149]
  [-0.00916927 -0.0327213 ]
  [-0.00916927 -0.0327213 ]
  [-0.00916927 -0.0327213 ]]

 [[-0.0256271   0.03285149]
  [-0.0256271   0.03285149]
  [-0.00916927 -0.0327213 ]
  [-0.00916927 -0.0327213 ]
  [-0.00916927 -0.0327213 ]]

 [[ 0.00674915 -0.00810628]
  [ 0.00674915 -0.00810628]
  [ 0.03029137  0.03085308]
  [-0.00916927 -0.0327213 ]
  [-0.00916927 -0.0327213 ]]

 [[ 0.03777539  0.01844103]
  [ 0.00409846 -0.04413558]
  [ 0.03777539  0.01844103]
  [-0.0256271   0.03285149]
  [ 0.03777539  0.01844103]]

 [[ 0.01649335 -0.03192105]
  [ 0.02853162 -0.00163345]
  [ 0.02927333  0.0295602 ]
  [ 0.01898333  0.01776576]
  [-0.00916927 -0.0327213 ]]

 [[ 0.04585977  0.00383325]
  [ 0.04585977  0.00383325]
  [-0.00916927 -0.0327213 ]
  [-0.00916927 -0.0327213 ]
  [-0.00916927 -0.0327213 ]]

 [[ 0.03875413  0.02734799]
  [ 0.03875413  0.02734799]
  [-0.00916927 -0.0327213 ]
  [-0.00916927 -0.0327213

In [ ]:
import tensorflow as tf
from tensorflow import keras

In [ ]:
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [ ]:
(X_train,y_train),(X_test,y_test) = imdb.load_data(num_words=10000)

In [ ]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [ ]:
X_train.shape

(25000, 50)

In [ ]:
model  = Sequential()
model.add(Embedding(10000,2))
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1,activation='sigmoid'))

model.summary()

Model: "sequential_15"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_19 (Embedding)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_7 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(X_train, y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 16s 18ms/step - acc: 0.5478 - loss: 0.6699 - val_acc: 0.7950 - val_loss: 0.4464
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 13s 17ms/step - acc: 0.8287 - loss: 0.3895 - val_acc: 0.8064 - val_loss: 0.4273
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 20s 17ms/step - acc: 0.8716 - loss: 0.3175 - val_acc: 0.8116 - val_loss: 0.4263
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 13s 17ms/step - acc: 0.8909 - loss: 0.2805 - val_acc: 0.8024 - val_loss: 0.4500
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 20s 16ms/step - acc: 0.9067 - loss: 0.2528 - val_acc: 0.7998 - val_loss: 0.4735


In [ ]:
model.evaluate(X_test,y_test)

782/782 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - acc: 0.8017 - loss: 0.4753


[0.4734596610069275, 0.799839973449707]

In [ ]:
model.predict(X_test)

782/782 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step


array([[0.32034844],
       [0.9750044 ],
       [0.747348  ],
       ...,
       [0.1949364 ],
       [0.00887098],
       [0.9184346 ]], dtype=float32)

In [ ]:
# embedding is one of the most used technique